service: python-lamda-sqs-server-starter

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-2
  stage: ${opt:stage, 'SIT'}
  tags:
    department: 'digital'
    service: 'image-resizer'
    environment: ${self:provider.stage}
  stackTags:
    department: 'digital'
    service: 'image-resizer'
    environment: ${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - '*/*'

functions:
  resize:
    handler: handler.get_image
    events:
      - http:
          path: 's3/{proxy+}'
          method: get
        
plugins:
  - serverless-python-requirements
  - serverless-domain-manager

params:
  SIT:
    customDomain:
      domainName: dev.assets.cougar.bauer-media.net.au
      basePath: ''
      stage: SIT
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2
      autoDomain: true
  PROD:
    customDomain:
      domainName: assets.digital.aremedia.net.au
      basePath: ''
      stage: PROD
      createRoute53Record: true
      endpointType: 'regional'
      securityPolicy: tls_1_2
      autoDomain: true      

custom:
  pythonRequirements:
    dockerizePip: non-linux
    slim: true
  customDomain: ${param:customDomain}
  
