name: Serverless Deploy

on:
  push:
    branches:
      - main
      - "feature/**"
      - "fix/**"
      - "dependabot/**"
      - "cci-/**"

jobs:
  serverless-deploy:
    env:
      BUILD_ENV: ${{ github.ref == 'refs/heads/main' && 'SIT' || 'SIT' }}
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'SIT' || 'SIT' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Python version from file
        id: python_version
        run: echo "PYTHON_VERSION=$(cat .python-version)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Print and verify env variables
        run: echo "BUILD_ENV=${{ env.BUILD_ENV }}"

      - name: Approval for deployment
        if: github.event_name == 'pull_request'
        uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: ${{ secrets.TOKEN_FOR_GIT }}

      - name: Install Serverless Plugins
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-dotenv-plugin && serverless plugin install --name serverless-offline && serverless plugin install --name serverless-python-requirements"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          BUILD_ENV: ${{ env.BUILD_ENV }}

      - name: Deploy Application
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless deploy --verbose --stage ${{ env.BUILD_ENV }} && serverless doctor"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
          BUILD_ENV: ${{ env.BUILD_ENV }}
